// Generated types from SFDR schema
// Do not edit this file directly - it is generated from JSON schema

import { FromSchema } from 'json-schema-to-ts';

// NayaOne ESG Data Integration Types
export interface NayaOneESGData {
  provider: 'nayaone';
  companyId: string;
  companyName: string;
  ticker?: string;
  sector?: string;
  industry?: string;
  country?: string;
  esgScore: {
    overall?: number;
    environmental?: number;
    social?: number;
    governance?: number;
  };
  ratings: {
    esgRating?: string;
    environmentalRating?: string;
    socialRating?: string;
    governanceRating?: string;
  };
  metrics: {
    carbonIntensity?: number;
    waterUsage?: number;
    wasteGeneration?: number;
    employeeTurnover?: number;
    boardDiversity?: number;
    executiveCompensation?: number;
  };
  sfdrIndicators: {
    principalAdverseImpacts: Record<string, any>;
    taxonomyAlignment: number;
    sustainableInvestment: number;
  };
  lastUpdated?: string;
  dataQuality: {
    completeness: number;
    reliability: 'high' | 'medium' | 'low';
    source: string;
  };
}

export interface ESGDataCollection {
  nayaone: NayaOneESGData[];
  bloomberg: any[];
  msci: any[];
  sustainalytics: any[];
}

export interface ESGDataQuality {
  totalRecords: number;
  completenessScore: number;
  reliabilityScore: number;
  lastUpdated: string;
  sourceBreakdown: Record<string, number>;
}

export interface SFDRRiskAnalysis {
  climateRisk: {
    score: number;
    factors: string[];
    mitigation: string[];
  };
  biodiversityRisk: {
    score: number;
    factors: string[];
    mitigation: string[];
  };
  socialRisk: {
    score: number;
    factors: string[];
    mitigation: string[];
  };
  governanceRisk: {
    score: number;
    factors: string[];
    mitigation: string[];
  };
  overallRiskScore: number;
  confidenceLevel: number;
}

export type SFDR = FromSchema<{
  "$id": "http://joinsynapes.com/schemas/sfdr.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "SFDR Disclosure",
  "description": "Schema for Sustainable Finance Disclosure Regulation (SFDR) reporting objects.",
  "type": "object",
  "properties": {
    "entityId": {
      "type": "string",
      "description": "Unique identifier for the reporting entity."
    },
    "disclosureDate": {
      "type": "string",
      "format": "date",
      "description": "Date of the SFDR disclosure (YYYY-MM-DD)."
    },
    "indicators": {
      "type": "array",
      "description": "List of principal adverse impact indicators.",
      "items": {
        "type": "object",
        "properties": {
          "indicatorId": {
            "type": "string",
            "description": "ID of the indicator (e.g., GHG emissions, gender pay gap)."
          },
          "value": {
            "type": [
              "number",
              "string",
              "boolean"
            ],
            "description": "Value of the indicator."
          },
          "unit": {
            "type": "string",
            "description": "Unit of measurement (if applicable)."
          }
        },
        "required": [
          "indicatorId",
          "value"
        ]
      },
      "minItems": 1
    },
    "productType": {
      "type": "string",
      "description": "Type of financial product (e.g., fund, portfolio, mandate)."
    },
    "esgStrategy": {
      "type": "string",
      "description": "Description of the ESG strategy applied."
    },
    "referencePeriod": {
      "type": "string",
      "description": "Reference period for the disclosure (e.g., 2024, Q1-2025)."
    },
    "notes": {
      "type": "string",
      "description": "Additional notes or comments."
    }
  },
  "required": [
    "entityId",
    "disclosureDate",
    "indicators"
  ],
  "additionalProperties": false
}>;
