import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { NavbarDemo } from '@/components/ui/navbar-menu-demo';
/**
 * Test page to demonstrate the navbar menu component
 */
const NavbarMenuTest = () => {
    return (_jsxs("div", { className: 'min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800', children: [_jsx(NavbarDemo, {}), _jsx("div", { className: 'pt-32 px-8', children: _jsxs("div", { className: 'max-w-4xl mx-auto', children: [_jsx("h1", { className: 'text-4xl font-bold text-center mb-8 text-gray-900 dark:text-white', children: "Synapses GRC Platform" }), _jsx("p", { className: 'text-lg text-center text-gray-600 dark:text-gray-300 mb-12', children: "Experience our AI-powered navigation menu designed for GRC professionals. Hover over the menu items above to see the interactive dropdowns." }), _jsxs("div", { className: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8', children: [_jsxs("div", { className: 'bg-white dark:bg-gray-800 p-6 rounded-lg shadow-lg', children: [_jsx("h3", { className: 'text-xl font-semibold mb-4 text-gray-900 dark:text-white', children: "AI-Powered Solutions" }), _jsx("p", { className: 'text-gray-600 dark:text-gray-300', children: "Our navbar showcases AI agents specifically designed for GRC workflows, including SFDR Navigator, AML Investigator, and Risk Analyzer." })] }), _jsxs("div", { className: 'bg-white dark:bg-gray-800 p-6 rounded-lg shadow-lg', children: [_jsx("h3", { className: 'text-xl font-semibold mb-4 text-gray-900 dark:text-white', children: "Smooth Animations" }), _jsx("p", { className: 'text-gray-600 dark:text-gray-300', children: "Built with Framer Motion for fluid transitions and professional user experience that matches enterprise GRC platform standards." })] }), _jsxs("div", { className: 'bg-white dark:bg-gray-800 p-6 rounded-lg shadow-lg', children: [_jsx("h3", { className: 'text-xl font-semibold mb-4 text-gray-900 dark:text-white', children: "React Router Integration" }), _jsx("p", { className: 'text-gray-600 dark:text-gray-300', children: "Fully adapted for React Router navigation, ensuring seamless integration with your existing Synapses platform routing." })] })] }), _jsxs("div", { className: 'mt-16 text-center', children: [_jsx("h2", { className: 'text-2xl font-bold mb-4 text-gray-900 dark:text-white', children: "Component Features" }), _jsxs("ul", { className: 'text-left max-w-2xl mx-auto space-y-2 text-gray-600 dark:text-gray-300', children: [_jsx("li", { children: "\u2705 Fully TypeScript compatible" }), _jsx("li", { children: "\u2705 Tailwind CSS styling with custom shadow-input" }), _jsx("li", { children: "\u2705 React Router Link integration" }), _jsx("li", { children: "\u2705 Framer Motion animations" }), _jsx("li", { children: "\u2705 Dark mode support" }), _jsx("li", { children: "\u2705 GRC-focused menu structure" }), _jsx("li", { children: "\u2705 Responsive design" }), _jsx("li", { children: "\u2705 Accessibility features" })] })] })] }) })] }));
};
export default NavbarMenuTest;
