import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// import React from 'react';
import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { CheckCircle2, Brain, Users, LineChart, ShieldCheck, Layers, Database } from 'lucide-react';
const Features = () => {
    return (_jsxs("div", { className: 'min-h-screen flex flex-col', children: [_jsx(Navbar, {}), _jsxs("div", { className: 'flex-grow', children: [_jsx("section", { className: 'bg-gradient-to-br from-synapse-primary to-synapse-secondary text-white py-20', children: _jsx("div", { className: 'container mx-auto px-4', children: _jsxs("div", { className: 'max-w-4xl mx-auto text-center', children: [_jsx("h1", { className: 'text-4xl md:text-5xl font-bold mb-6', children: "Platform Features" }), _jsx("p", { className: 'text-xl md:text-2xl opacity-90 leading-relaxed', children: "Discover the comprehensive suite of tools that make Synapse the leading platform for GRC professionals." }), _jsxs("div", { className: 'mt-10 flex flex-col sm:flex-row justify-center gap-4', children: [_jsx(Button, { size: 'lg', className: 'bg-white text-synapse-primary hover:bg-white/90', children: "Request a Demo" }), _jsx(Button, { size: 'lg', variant: 'outline', className: 'border-white text-white hover:bg-white/10', children: "Join Waitlist" })] })] }) }) }), _jsx("section", { className: 'py-20', children: _jsxs("div", { className: 'container mx-auto px-4', children: [_jsxs("div", { className: 'text-center mb-16', children: [_jsx(Badge, { className: 'mb-4', children: "Core Capabilities" }), _jsx("h2", { className: 'text-3xl font-bold mb-4', children: "Comprehensive GRC Intelligence" }), _jsx("p", { className: 'text-lg text-gray-600 max-w-3xl mx-auto', children: "Our platform combines AI-powered insights, specialized knowledge, and community connections to streamline your compliance workflows." })] }), _jsx("div", { className: 'grid md:grid-cols-2 lg:grid-cols-3 gap-8 max-w-6xl mx-auto', children: [
                                        {
                                            icon: _jsx(Brain, { className: 'h-8 w-8 text-synapse-primary' }),
                                            title: 'AI Compliance Copilot',
                                            description: 'Dara, our AI assistant, analyzes regulations and provides actionable insights tailored to your specific compliance needs.'
                                        },
                                        {
                                            icon: _jsx(Database, { className: 'h-8 w-8 text-synapse-primary' }),
                                            title: 'Regulatory Knowledge Base',
                                            description: 'Access a comprehensive library of global regulations, frameworks, and standards with expert interpretations.'
                                        },
                                        {
                                            icon: _jsx(Users, { className: 'h-8 w-8 text-synapse-primary' }),
                                            title: 'GRC Community Network',
                                            description: 'Connect with peers, share insights, and collaborate with other compliance professionals facing similar challenges.'
                                        },
                                        {
                                            icon: _jsx(LineChart, { className: 'h-8 w-8 text-synapse-primary' }),
                                            title: 'Compliance Analytics',
                                            description: 'Visualize your compliance posture with real-time dashboards and reports for informed decision-making.'
                                        },
                                        {
                                            icon: _jsx(ShieldCheck, { className: 'h-8 w-8 text-synapse-primary' }),
                                            title: 'Control Mapping',
                                            description: 'Map controls across multiple frameworks to streamline audits and reduce duplicate compliance efforts.'
                                        },
                                        {
                                            icon: _jsx(Layers, { className: 'h-8 w-8 text-synapse-primary' }),
                                            title: 'Workflow Automation',
                                            description: 'Automate routine compliance tasks, notifications, and approvals to improve efficiency and reduce errors.'
                                        }
                                    ].map((feature, index) => (_jsxs(Card, { className: 'p-6 hover:shadow-md transition-shadow', children: [_jsx("div", { className: 'rounded-full bg-blue-50 p-3 w-fit mb-4', children: feature.icon }), _jsx("h3", { className: 'font-bold text-xl mb-2', children: feature.title }), _jsx("p", { className: 'text-gray-600', children: feature.description })] }, index))) })] }) }), _jsx("section", { className: 'py-20 bg-gray-50', children: _jsxs("div", { className: 'container mx-auto px-4', children: [_jsxs("div", { className: 'text-center mb-16', children: [_jsx(Badge, { className: 'mb-4', children: "Explore Features" }), _jsx("h2", { className: 'text-3xl font-bold mb-4', children: "Designed for GRC Professionals" }), _jsx("p", { className: 'text-lg text-gray-600 max-w-3xl mx-auto', children: "Each feature is built to address specific challenges faced by compliance teams." })] }), _jsx("div", { className: 'max-w-6xl mx-auto', children: _jsxs(Tabs, { defaultValue: 'ai', className: 'w-full', children: [_jsxs(TabsList, { className: 'grid grid-cols-4 gap-4 mb-12', children: [_jsx(TabsTrigger, { value: 'ai', className: 'py-4', children: "AI Copilot" }), _jsx(TabsTrigger, { value: 'knowledge', className: 'py-4', children: "Knowledge Base" }), _jsx(TabsTrigger, { value: 'community', className: 'py-4', children: "Community" }), _jsx(TabsTrigger, { value: 'analytics', className: 'py-4', children: "Analytics" })] }), _jsx(TabsContent, { value: 'ai', className: 'pt-6', children: _jsxs("div", { className: 'grid md:grid-cols-2 gap-12 items-center', children: [_jsxs("div", { children: [_jsx("h3", { className: 'text-2xl font-bold mb-4', children: "AI-Powered Compliance Assistance" }), _jsx("p", { className: 'text-gray-600 mb-6', children: "Dara is more than just a chatbot. Built on advanced language models and trained on millions of regulatory documents, Dara provides contextually relevant guidance for your specific compliance scenarios." }), _jsx("ul", { className: 'space-y-3', children: [
                                                                        'Ask complex regulatory questions in plain language',
                                                                        'Receive interpretations of new regulations and their impact',
                                                                        'Get step-by-step guidance for compliance processes',
                                                                        'Generate policy templates tailored to your organization',
                                                                        'Analyze documents for potential compliance gaps'
                                                                    ].map((item, i) => (_jsxs("li", { className: 'flex items-start', children: [_jsx(CheckCircle2, { className: 'h-5 w-5 text-green-500 mt-0.5 mr-2 flex-shrink-0' }), _jsx("span", { children: item })] }, i))) })] }), _jsx("div", { className: 'bg-white rounded-lg shadow-lg overflow-hidden border border-gray-100', children: _jsx("img", { src: '/placeholder.svg', alt: 'AI Copilot Interface', className: 'w-full h-auto' }) })] }) }), _jsx(TabsContent, { value: 'knowledge', className: 'pt-6', children: _jsxs("div", { className: 'grid md:grid-cols-2 gap-12 items-center', children: [_jsx("div", { className: 'order-2 md:order-1 bg-white rounded-lg shadow-lg overflow-hidden border border-gray-100', children: _jsx("img", { src: '/placeholder.svg', alt: 'Knowledge Base Interface', className: 'w-full h-auto' }) }), _jsxs("div", { className: 'order-1 md:order-2', children: [_jsx("h3", { className: 'text-2xl font-bold mb-4', children: "Comprehensive Regulatory Knowledge" }), _jsx("p", { className: 'text-gray-600 mb-6', children: "Access the most up-to-date regulatory information from around the world, organized and searchable to find exactly what you need, when you need it." }), _jsx("ul", { className: 'space-y-3', children: [
                                                                        'Global coverage of regulations across industries and jurisdictions',
                                                                        'Regular updates when regulatory changes occur',
                                                                        'Expert annotations and practical interpretations',
                                                                        'Advanced search capabilities with filters and bookmarking',
                                                                        'Customizable alerts for regulations relevant to your business'
                                                                    ].map((item, i) => (_jsxs("li", { className: 'flex items-start', children: [_jsx(CheckCircle2, { className: 'h-5 w-5 text-green-500 mt-0.5 mr-2 flex-shrink-0' }), _jsx("span", { children: item })] }, i))) })] })] }) }), _jsx(TabsContent, { value: 'community', className: 'pt-6', children: _jsxs("div", { className: 'grid md:grid-cols-2 gap-12 items-center', children: [_jsxs("div", { children: [_jsx("h3", { className: 'text-2xl font-bold mb-4', children: "Connect with GRC Professionals" }), _jsx("p", { className: 'text-gray-600 mb-6', children: "Join a vibrant community of compliance professionals who share knowledge, best practices, and opportunities. Network with peers facing similar challenges." }), _jsx("ul", { className: 'space-y-3', children: [
                                                                        'Discussion forums organized by industry and regulatory domain',
                                                                        'Private messaging to connect directly with peers',
                                                                        'Expert Q&A sessions with industry leaders',
                                                                        'Career opportunities and professional development resources',
                                                                        'Regional and special interest groups for focused networking'
                                                                    ].map((item, i) => (_jsxs("li", { className: 'flex items-start', children: [_jsx(CheckCircle2, { className: 'h-5 w-5 text-green-500 mt-0.5 mr-2 flex-shrink-0' }), _jsx("span", { children: item })] }, i))) })] }), _jsx("div", { className: 'bg-white rounded-lg shadow-lg overflow-hidden border border-gray-100', children: _jsx("img", { src: '/placeholder.svg', alt: 'Community Interface', className: 'w-full h-auto' }) })] }) }), _jsx(TabsContent, { value: 'analytics', className: 'pt-6', children: _jsxs("div", { className: 'grid md:grid-cols-2 gap-12 items-center', children: [_jsx("div", { className: 'order-2 md:order-1 bg-white rounded-lg shadow-lg overflow-hidden border border-gray-100', children: _jsx("img", { src: '/placeholder.svg', alt: 'Analytics Dashboard', className: 'w-full h-auto' }) }), _jsxs("div", { className: 'order-1 md:order-2', children: [_jsx("h3", { className: 'text-2xl font-bold mb-4', children: "Data-Driven Compliance Insights" }), _jsx("p", { className: 'text-gray-600 mb-6', children: "Visualize your compliance posture with intuitive dashboards and reports that help you identify gaps, track progress, and demonstrate effectiveness to stakeholders." }), _jsx("ul", { className: 'space-y-3', children: [
                                                                        'Real-time compliance status dashboards',
                                                                        'Customizable reports for different stakeholders',
                                                                        'Trend analysis to track improvement over time',
                                                                        'Risk heat maps to identify priority areas',
                                                                        'Automated board and executive reporting'
                                                                    ].map((item, i) => (_jsxs("li", { className: 'flex items-start', children: [_jsx(CheckCircle2, { className: 'h-5 w-5 text-green-500 mt-0.5 mr-2 flex-shrink-0' }), _jsx("span", { children: item })] }, i))) })] })] }) })] }) })] }) }), _jsx("section", { className: 'bg-synapse-primary py-16', children: _jsx("div", { className: 'container mx-auto px-4', children: _jsxs("div", { className: 'max-w-4xl mx-auto text-center text-white', children: [_jsx("h2", { className: 'text-3xl font-bold mb-4', children: "Ready to transform your GRC experience?" }), _jsx("p", { className: 'text-xl opacity-90 mb-8', children: "Join the thousands of compliance professionals already using Synapse to simplify their workflows." }), _jsxs("div", { className: 'flex flex-col sm:flex-row justify-center gap-4', children: [_jsx(Button, { size: 'lg', className: 'bg-white text-synapse-primary hover:bg-white/90', children: "Request a Demo" }), _jsx(Button, { size: 'lg', variant: 'outline', className: 'border-white text-white hover:bg-white/10', children: "Learn More" })] })] }) }) })] }), _jsx(Footer, {})] }));
};
export default Features;
