import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// React import removed - using modern JSX transform
import { BadgeCheck, GamepadIcon, Users, BookOpen } from 'lucide-react';
import { Link } from 'react-router-dom';
import { blogPosts } from '@/data/blogData';
export const StatusCards = () => {
    // Count the number of articles
    const articleCount = blogPosts.length;
    return (_jsxs("div", { className: 'flex gap-1 h-[15%] mb-1', children: [_jsxs("div", { className: 'flex-1 bg-white rounded-md p-1 border border-gray-100 shadow-sm cursor-pointer hover:shadow-md transition-shadow', children: [_jsxs("div", { className: 'flex items-center gap-0.5', children: [_jsx(BadgeCheck, { size: 7, className: 'text-blue-500' }), _jsx("div", { className: 'text-[6px] text-gray-600', children: "Badges" })] }), _jsx("div", { className: 'text-gray-800 text-[10px] font-medium', children: "12 New" }), _jsx("div", { className: 'h-0.5 w-full mt-1 bg-gradient-to-r from-blue-300 to-blue-500 rounded-full' })] }), _jsxs("div", { className: 'flex-1 bg-white rounded-md p-1 border border-gray-100 shadow-sm cursor-pointer hover:shadow-md transition-shadow', children: [_jsxs("div", { className: 'flex items-center gap-0.5', children: [_jsx(GamepadIcon, { size: 7, className: 'text-purple-500' }), _jsx("div", { className: 'text-[6px] text-gray-600', children: "Gamification" })] }), _jsx("div", { className: 'text-gray-800 text-[10px] font-medium', children: "New Games" }), _jsx("div", { className: 'h-0.5 w-full mt-1 bg-gradient-to-r from-purple-300 to-purple-500 rounded-full' })] }), _jsxs(Link, { to: '/resources/blog', className: 'flex-1 bg-white rounded-md p-1 border border-gray-100 shadow-sm cursor-pointer hover:shadow-md transition-shadow', children: [_jsxs("div", { className: 'flex items-center gap-0.5', children: [_jsx(BookOpen, { size: 7, className: 'text-green-500' }), _jsx("div", { className: 'text-[6px] text-gray-600', children: "GRC Blog" })] }), _jsxs("div", { className: 'text-gray-800 text-[10px] font-medium', children: [articleCount, " Articles"] }), _jsx("div", { className: 'h-0.5 w-full mt-1 bg-gradient-to-r from-green-300 to-green-500 rounded-full' })] }), _jsxs("div", { className: 'flex-1 bg-white rounded-md p-1 border border-gray-100 shadow-sm cursor-pointer hover:shadow-md transition-shadow', children: [_jsxs("div", { className: 'flex items-center gap-0.5', children: [_jsx(Users, { size: 7, className: 'text-amber-500' }), _jsx("div", { className: 'text-[6px] text-gray-600', children: "Forum Activity" })] }), _jsx("div", { className: 'text-gray-800 text-[10px] font-medium', children: "5 New" }), _jsx("div", { className: 'h-0.5 w-full mt-1 bg-gradient-to-r from-amber-300 to-amber-500 rounded-full' })] })] }));
};
