import { FromSchema } from 'json-schema-to-ts';
import * as fs from 'fs';
import * as path from 'path';

const schemaFile = path.join(process.cwd(), 'src/schemas/sfdr.json');
const outputFile = path.join(process.cwd(), 'src/types/sfdr.ts');

const schema = JSON.parse(fs.readFileSync(schemaFile, 'utf-8'));

const output = `// Generated types from SFDR schema\n// Do not edit this file directly - it is generated from JSON schema\n\nimport { FromSchema } from 'json-schema-to-ts';\n\nexport type SFDR = FromSchema<${JSON.stringify(schema, null, 2)}>;\n`;

fs.writeFileSync(outputFile, output);
console.log('SFDR types generated successfully!');
