// This file is automatically generated. Do not edit it directly.
// Trigger nodemon restart
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://hnwwykttyzfvflmcswjk.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhud3d5a3R0eXpmdmZsbWNzd2prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjA1NTgsImV4cCI6MjA2MDI5NjU1OH0.50J8-EdyyjDGfOLOoMgzoXCgP7URWZTJZkqlb0Zxwos';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Lazy initialization function for server-side usage
let _supabaseInstance: ReturnType<typeof createClient<Database>> | null = null;

export const getSupabase = () => {
  if (!_supabaseInstance) {
    // Always use hardcoded values for development
    _supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
  }
  return _supabaseInstance;
};
