name: Deploy Synapse SPA

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: '18'
  CDK_VERSION: '2.155.0'

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build application
        run: npm run build
        env:
          VITE_API_BASE_URL: ${{ github.ref == 'refs/heads/main' && secrets.VITE_API_BASE_URL_PROD || secrets.VITE_API_BASE_URL_DEV }}
          VITE_API_TIMEOUT: ${{ secrets.VITE_API_TIMEOUT }}

  deploy-dev:
    name: Deploy to Development
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}

      - name: Install CDK
        run: npm install -g aws-cdk@${{ env.CDK_VERSION }}

      - name: Install application dependencies
        run: npm ci

      - name: Install infrastructure dependencies
        run: |
          cd infrastructure
          npm ci

      - name: Set up SSM parameters
        run: |
          aws ssm put-parameter --name "/synapse/dev/api-base-url" --value "${{ secrets.VITE_API_BASE_URL_DEV }}" --type "String" --overwrite
          aws ssm put-parameter --name "/synapse/dev/api-timeout" --value "${{ secrets.VITE_API_TIMEOUT }}" --type "String" --overwrite

      - name: Build application
        run: npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL_DEV }}
          VITE_API_TIMEOUT: ${{ secrets.VITE_API_TIMEOUT }}

      - name: Deploy CDK stack
        run: |
          cd infrastructure
          npm run deploy:dev
        env:
          CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
          CDK_DEFAULT_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}

  deploy-production:
    name: Deploy to Production
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}

      - name: Install CDK
        run: npm install -g aws-cdk@${{ env.CDK_VERSION }}

      - name: Install application dependencies
        run: npm ci

      - name: Install infrastructure dependencies
        run: |
          cd infrastructure
          npm ci

      - name: Set up SSM parameters
        run: |
          aws ssm put-parameter --name "/synapse/prod/api-base-url" --value "${{ secrets.VITE_API_BASE_URL_PROD }}" --type "String" --overwrite
          aws ssm put-parameter --name "/synapse/prod/api-timeout" --value "${{ secrets.VITE_API_TIMEOUT }}" --type "String" --overwrite

      - name: Build application
        run: npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL_PROD }}
          VITE_API_TIMEOUT: ${{ secrets.VITE_API_TIMEOUT }}

      - name: Deploy CDK stack
        run: |
          cd infrastructure
          npm run deploy:prod
        env:
          CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
          CDK_DEFAULT_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}
